GET https://api.kinopoisk.dev/v1.4/movie/search?query=капитан врунгель
X-API-KEY: {{token}}

###
GET https://api.kinopoisk.dev/v1.4/movie/79920
X-API-KEY: {{token}}

###
GET https://api.kinopoisk.dev/v1.4/season?movieId=43254&limit=100
X-API-KEY: {{token}}

### Южный парк
GET https://api.kinopoisk.dev/v1.4/season?movieId=161252&limit=100
X-API-KEY: {{token}}